package labs_examples.exception_handling.labs;

//public class MethodThrow {

   // public class ThrowingExceptionsExample {
        //public void main(String[] args){
        //    try {
         //       methodOne();
         //   } catch(ArrayIndexOutOfBoundsException exc){

          //      System.out.println("exception caught");
          //  }
       // }

      //  public void methodOne() throws ArrayIndexOutOfBoundsException {

       //     methodTwo();
      //  }


     //   public static void methodTwo() throws ArrayIndexOutOfBoundsException {
       //     int[] nums = {1,2,3};
         //   try {
        //        int x = nums[10];
         //   } catch (ArrayIndexOutOfBoundsException exc){
         //       System.out.println("Caught in methodTwo");
         //       System.out.println("Throwing exception back to methodOne");
         //       throw exc;
         //   }
       // }
  //  }



//}
